version: '3'

services:
  symfony-skeleton-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5566:5432"
  symfony-skeleton:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
    env_file: ../.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - symfony-skeleton-database
    volumes:
      - ../:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true